### ISSUE TITLE
Archlinux, java et swift-explorer

### ISSUE THREAD

**Issue by widowild1** [roikku/swift-explorer#46]
Bonjour,
je tente de lancer swift-explorer sous archlinux, mais j'ai ces erreurs qui défilent:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/swiftexplorer/SwiftExplorer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

$  java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (Arch Linux build 7.u75_2.5.4-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

je passe en jre8

$  java -version
openjdk version "1.8.0_40"
OpenJDK Runtime Environment (build 1.8.0_40-b20)
OpenJDK 64-Bit Server VM (build 25.40-b23, mixed mode)

$  java -jar ./SwiftExplorer-1.0.7-jar-with-dependencies.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Platform
	at org.swiftexplorer.SwiftExplorer.main(SwiftExplorer.java:79)
Caused by: java.lang.ClassNotFoundException: javafx.application.Platform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

avez vous une idée pour le lancer?

**Comment by widowild1** [comment]
juste le jre de https://aur.archlinux.org/packages/jre/ fonctionne,

j'ai donc exporté le swift-explorer sous archlinux:

https://aur.archlinux.org/packages/swift-explorer/
