### ISSUE TITLE
Unable to lunch the App under Linux (Fedora 21)

### ISSUE THREAD

**Issue by adakite** [roikku/swift-explorer#47]
Trying to run Swift Explorer leads me to the following errors: 

java  -jar SwiftExplorer-1.0.7-jar-with-dependencies.jarException in thread "main" java.lang.NoClassDefFoundError: javafx/application/Platform
	at org.swiftexplorer.SwiftExplorer.main(SwiftExplorer.java:79)
Caused by: java.lang.ClassNotFoundException: javafx.application.Platform
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

My JRE is up-to-date as the rest of my distro. What's wrong with this package?

**Comment by roikku** [comment]
I suspect the JRE you use does not implement [JavaFX](http://en.wikipedia.org/wiki/JavaFX), which is required.

**Comment by adakite** [comment]
I installed the package from Oracle website which mentions JavaFX....Does swift explorer work on Linux?

**Comment by adakite** [comment]
okay, it appears that on Fedora, yum (i.e., the package manager) does not install JRE/JDK at the same place that Oracle does, and so two different versions of the same packages are present parallely and one does not content JFX library. 

Problem solved
