### ISSUE TITLE
Can't launch the jar under Java 8 on Ubuntu

### ISSUE THREAD

**Issue by adimz** [roikku/swift-explorer#54]
Here is the term output.
What's wrong then please?

alain@sd-53712:~/Desktop$ uname -a
Linux sd-53712 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
alain@sd-53712:~/Downloads$ chmod 777 SwiftExplorer-1.0.7-jar-with-dependencies.jar 
alain@sd-53712:~/Downloads$ ls -l
total 17128
-rwxrwxrwx 1 alain alain 17536872 Oct  7 11:42 SwiftExplorer-1.0.7-jar-with-dependencies.jar
alain@sd-53712:~/Downloads$ java -jar SwiftExplorer-1.0.7-jar-with-dependencies.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Platform
	at org.swiftexplorer.SwiftExplorer.main(SwiftExplorer.java:79)
Caused by: java.lang.ClassNotFoundException: javafx.application.Platform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
alain@sd-53712:~/Downloads$ java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
alain@sd-53712:~/Downloads$ 

Regards

Alain

**Comment by cicithesquirrel** [comment]
I had this too and solved it with manually installing OpenJFX: `sudo apt-get install openjfx`

It turns out that default [OpenJDK](http://openjdk.java.net/) does not come with [OpenJFX](http://openjdk.java.net/projects/openjfx/) (JavaFX implementation) by default.

**Comment by Cyrille37** [comment]
This JavaFX dependency is not so sweat...
The Ubuntu 14.04 LTS does not know about:
```
$ sudo apt-get install openjfx
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet openjfx
```

**Comment by furlongm** [comment]
Getting the same error on opensuse:

$ java -jar SwiftExplorer-1.0.8-jar-with-dependencies.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Platform
        at org.swiftexplorer.SwiftExplorer.main(SwiftExplorer.java:79)
Caused by: java.lang.ClassNotFoundException: javafx.application.Platform
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

There's no openjfx package packaged for opensuse either.
