### ISSUE TITLE
Is Fedora supported?

### ISSUE THREAD

**Issue by cortopy** [roikku/swift-explorer#57]
I've just started using swiftexplorer. It works great in Ubuntu, but unfortunately it doesn't play well in Fedora. I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Platform
	at org.swiftexplorer.SwiftExplorer.main(SwiftExplorer.java:79)
Caused by: java.lang.ClassNotFoundException: javafx.application.Platform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
 
I'm not a Java developer, but I'm guessing this is because OpenJDK included in Fedora doesn't include proprietary parts of Java. Is my guess right?

**Comment by murf0** [comment]
Hi!
Seems like the same error as: https://github.com/roikku/swift-explorer/issues/54
Can you try and install openjfx?
br
