### ISSUE TITLE
Can't launch the jar under Java 10 on Ubuntu even with OpenJFX installed

### ISSUE THREAD

**Issue by Jeannotisintheplace** [roikku/swift-explorer#84]
Hello,
i unfortunately get this error message:

java -jar SwiftExplorer-1.0.9-jar-with-dependencies.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Platform
	at org.swiftexplorer.SwiftExplorer.main(SwiftExplorer.java:79)
Caused by: java.lang.ClassNotFoundException: javafx.application.Platform
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 1 more

whereas OpenJFX package is installed

Below my java -version (Ubuntu 18.04)
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)

Thanks for your helo

**Comment by osallou** [comment]
My 2 cents... Javafx has been removed from jdk and packaged as separate library.
I think you need to get it and add it to classpath (not tested)

**Comment by Jeannotisintheplace** [comment]
Solution was to downgrade to previous i do version. Thanks.

JR

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------
